name: Certificates Dumper
description: Dumps Let's Encrypt certificates of a specified domain to .pem and .key files which Traefik stores in acme.json.
instructions: Make sure that your server has a directory for certificates, otherwise this service will not work. You can use `sudo mkdir /etc/letsencrypt/live/` to make it work with the default service settings.
changeLog:
  - date: 2023-01-05
    description: first release
links:
  - label: Documentation
    url: https://github.com/kereis/traefik-certs-dumper#usage
  - label: Github
    url: https://github.com/kereis/traefik-certs-dumper
contributors:
  - name: Kotyarishka
    url: https://github.com/kotyarishka
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - certificatesLocation
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: certdumper
    appServiceImage:
      type: string
      title: App Service Image
      default: humenius/traefik-certs-dumper:1.6.1

    certificatesLocation:
      type: string
      title: Certificates location
      default: /etc/letsencrypt/live/
      descritption: Certificates will be located at <location>/<domain>/

    # DOMAIN
    domainsToDump:
      type: string
      title: Domains to dump
      description: Include the domains for which you want to obtain a certificate, separated by commas. Leave the field blank if you want certificates for all domains at once.

    # PRIVATE_KEY_FILE_NAME
    privateKeyFilename:
      type: string
      title: Private key file name
      default: privkey
    # PRIVATE_KEY_FILE_EXT
    privateKeyExt:
      type: string
      title: Private key file extension
      default: .pem

    # CERTIFICATE_FILE_NAME
    certificateFilename:
      type: string
      title: Certificate file name
      default: fullchain
    # CERTIFICATE_FILE_EXT
    certificateExt:
      type: string
      title: Certificate file extension
      default: .pem
